// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6ePUqhNP5yprmyV5WzWYpliwEnq-VhZs',
    appId: '1:343429360131:android:80add1c6a9101cd237bc36',
    messagingSenderId: '343429360131',
    projectId: 'kindred-chatbot',
    storageBucket: 'kindred-chatbot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5iptxtlrwTVa8LP2ixRe9-3EV_8T1No0',
    appId: '1:343429360131:ios:867071779e6af88d37bc36',
    messagingSenderId: '343429360131',
    projectId: 'kindred-chatbot',
    storageBucket: 'kindred-chatbot.firebasestorage.app',
    androidClientId: '343429360131-k2o48t7op0qarvkgtbav1mh5vak1pdio.apps.googleusercontent.com',
    iosClientId: '343429360131-kd8ha7pef6m3hh2n5jopio3adjrv5b98.apps.googleusercontent.com',
    iosBundleId: 'com.example.kindredChatbot',
  );

}